#服务端口号
server:
  port: 8888
# 应用名称
spring:
  application:
    name: config-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #useSSL=false 不使用安全套接字  serverTimeZone=GMT%2B8 设置服务器时区 东八区
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: client1! 
eureka:
  client: #客户端注册，将服务注册到哪一个注册中的去
    service-url:
      defaultZone: http://localhost:8071/eureka,http://localhost:8072/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔2（默认是30秒）
    lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
    #instance-id: Eureka_consumer_8070  #自定义服务名称
    prefer-ip-address: true  #访问路径可以显示IP地址
